### ISSUE TITLE
[CSS Imports] Clarification on how the Draft 1 proposal differs from the Ruby Sass implementation

### ISSUE THREAD

**Issue by xzyfer** [sass/language#5]
It would be nice to explicitly call out how the [CSS Imports: Draft 1](https://github.com/sass/language/blob/2f75a8d09dd43b6ae184441bdca5a5b2c39a6939/proposal/css-imports.md) differs from the existing Ruby Sass implementation.

I'm using Ruby Sass as it was the (loose) reference for the LibSass implementation. We (the LibSass team) are seeking clarification on the work required to align with the spec (ignoring the current mis-alignments).

**Comment by nex3** [comment]
Other than plain CSS imports, the algorithm is designed to match the current behavior of imports in Ruby Sass and Dart Sass. The goal of writing out the entire import algorithm is to make that behavior more formal and explicit, not to change it. I'll update the proposal to make this clearer.

That said, the proposal does differ from Ruby Sass's *implementation*, in that it operates on URLs where Ruby Sass operates on plain strings and file paths. As long as you're only dealing with filesystem imports, this isn't a change in functionality since `file:` URLs correspond to paths on disk and vice versa. Once we start formalizing how importers should work, though, stuff that's just implementation details here may be more relevant to user-visible behavior.
