### ISSUE TITLE
What should the syntax for module mixins be?

### ISSUE THREAD

**Issue by nex3** [sass/language#9]
Draft 2 of the proposal allows a [module mixin](https://github.com/sass/language/tree/proposal.module-system.draft-2/#module-mixins) to be defined using the syntax `@use "susy" mixin`. This defines a mixin with the same name as the module's prefix that, when included, injects the module's CSS at that point in the document. This is intended to satisfy the use-case currently handled using [nested imports](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_import), where a user wants to scope a chunk of upstream CSS within a specific selector or media query.

I'm not sure this is the best syntax to use, though. Creating an implicit mixin feels weird, especially because it means `namespace` and `namespace.member` will both be meaningful identifiers, but the latter won't actually be referring to a member of the former. It would also be the only instance under the new module system where a `@use` without `no-prefix` would create an identifier that's not part of a unique namespace.

**Note:** I'm considering this discussion largely orthogonal to https://github.com/sass/language/issues/8. In any of these proposals, the module mixin may or may not allow configuration parameters to be passed.

## Possible Options

1. ### Keep the existing syntax

   ```scss
   @use "susy" mixin;

   .susy {
     @include susy;
   }
   ```

2. ### Add a meta mixin and a `silent` modifier

   This mixin would take the namespace or URL of the module and include its CSS. This way we don't pollute the top-level namespace. It would also require adding a modifier to `@use` to tell it not to generate any CSS on its own, but that may be useful anyway.

   ```scss
   @use "susy" silent;
   @use "sass:meta";

   .susy {
     @include meta.module-css("susy");
   }
   ```

3. ### Add a meta mixin that can dynamically load files

   If the meta mixin can take a module URL, it raises a new question: why not just allow it to take *any* URL, not just one that has a `@use` declaration in the same file? This dovetails with the planned [`load()`](https://github.com/sass/sass/issues/739#issuecomment-279093113) function nicely; it would effectively be a shorthand for `@include meta.include(map.get(meta.load($url), "css"))`.

   It also dodges most of the downsides of dynamic includes, because it explicitly *does not* introduce any new names to the file that includes it. Static analysis therefore remains tractable (although, as with `load()`, it does become impossible to statically determine the set of files a stylesheet depends on).

   ```scss
   @use "sass:meta";

   .susy {
     @include meta.load-css("susy");
   }
   ```

**Comment by nex3** [comment]
@nshahan I don't think it's any worse than [the `load()` function](https://github.com/sass/sass/issues/739#issuecomment-279093113), which we're already planning to add. It's kind of a parallel concept to isolates in Dart: you can load them dynamically, but in a strict build system you need to explicitly depend on everything you might load dynamically.

**Comment by jelbourn** [comment]
I would actually propose an alternate approach here, with the goal of creating a generally more strict and explicit system to combining concrete CSS trees: `@use` **always** encapsulates the CSS tree of the target into a mixin (or similar construct). This admittedly further departs from the existing `@import` mechanics, but pushes for a more explicit ecosystem. Since `@use` is a totally new syntax, it's the perfect time to change how people think about importing other Sass files.

The motivations here are:
* Prevent people from accidentally pulling in concrete styles when they only intended to `@use` mixins/variables/functions. I have seen this happen on multiple occasions, with people unknowingly ballooning their CSS payload size.
* Impose consistency by avoiding having two different ways in which `@use` can interact with CSS trees. Having exactly one mental model for `@use` makes it easier to internalize.
* Align Sass with other languages in discouraging/minimizing side-effects. 

Since `@import` is a standard CSS feature, it would then make sense to continue using `@import` to do what it does today (always pulling in the full CSS tree of the target).

**Comment by nex3** [comment]
I think I agree that a zero-side-effect approach to library design is a good one, but I'm very concerned with how backwards-incompatible it would be to encode that into the language. Not only does it add a lot of boilerplate to users' stylesheets if they migrate without refactoring, but it requires users to migrate their *understanding* of how Sass projects should be structured. Even if that migration is positive (and I believe it probably is), that adds a *lot* of friction to what's already going to be a difficult ecosystem-wide migration.

At a higher level, the reason I'm so concerned with migration cost is that there's a real possibility that, if the friction around `@use` is high enough, libraries just won't adopt it. And since it's a feature all about interactions *between* Sass files, it really needs most of the ecosystem to buy into it to be successful in the long run. I'm very wary of using it as a lever to try to change people's interactions with Sass, because I'm worried that lever will push the other way and just push people away from `@use`.

**Comment by nex3** [comment]
Now that the module system proposal has been accepted, this has been definitively decided: **module mixins are included using a special built in `meta.load-css()` mixin**.
